# Generated by Django 5.0.1 on 2024-01-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('profile_pic', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'profile_info',
            },
        ),
    ]
